/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeliverymethodRouteImport } from './routes/deliverymethod'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecipientRouteImport } from './routes/recipient'
import { Route as SenderRouteImport } from './routes/sender'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverymethodRoute = DeliverymethodRouteImport.update({
  id: '/deliverymethod',
  path: '/deliverymethod',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientRoute = RecipientRouteImport.update({
  id: '/recipient',
  path: '/recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const SenderRoute = SenderRouteImport.update({
  id: '/sender',
  path: '/sender',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deliverymethod': typeof DeliverymethodRoute
  '/profile': typeof ProfileRoute
  '/recipient': typeof RecipientRoute
  '/sender': typeof SenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deliverymethod': typeof DeliverymethodRoute
  '/profile': typeof ProfileRoute
  '/recipient': typeof RecipientRoute
  '/sender': typeof SenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deliverymethod': typeof DeliverymethodRoute
  '/profile': typeof ProfileRoute
  '/recipient': typeof RecipientRoute
  '/sender': typeof SenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deliverymethod' | '/profile' | '/recipient' | '/sender'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deliverymethod' | '/profile' | '/recipient' | '/sender'
  id:
    '__root__' | '/' | '/deliverymethod' | '/profile' | '/recipient' | '/sender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliverymethodRoute: typeof DeliverymethodRoute
  ProfileRoute: typeof ProfileRoute
  RecipientRoute: typeof RecipientRoute
  SenderRoute: typeof SenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverymethod': {
      id: '/deliverymethod'
      path: '/deliverymethod'
      fullPath: '/deliverymethod'
      preLoaderRoute: typeof DeliverymethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipient': {
      id: '/recipient'
      path: '/recipient'
      fullPath: '/recipient'
      preLoaderRoute: typeof RecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sender': {
      id: '/sender'
      path: '/sender'
      fullPath: '/sender'
      preLoaderRoute: typeof SenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliverymethodRoute: DeliverymethodRoute,
  ProfileRoute: ProfileRoute,
  RecipientRoute: RecipientRoute,
  SenderRoute: SenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
